# Generated by Django 5.0.6 on 2025-11-05 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Gasto', 'Gasto')], max_length=20)),
                ('archivo_origen', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
