# Generated by Django 5.0.6 on 2025-11-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['-fecha']},
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='tipo',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='abono',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='cargo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
